services:
  db:
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squid-archive

  ingest:
    volumes:
      - "./types-mainnet.json:/config/types-mainnet.json"
    command: [
      "--types-bundle", "/config/types-mainnet.json",
      "-e", "wss://zeitgeist-rpc.dwellir.com",
      "-e", "wss://zeitgeist.api.onfinality.io/public-ws",
      "-c", "10", # allow up to 20 pending requests for the above endpoint (default is 5)
      "--out", "postgres://postgres:postgres@db:5432/squid-archive"
    ]
    ports:
      - 9090:9090

  gateway:
    environment:
      RUST_LOG: "substrate_gateway=info,actix_server=info"
    command: [
      "--database-url", "postgres://postgres:postgres@db:5432/squid-archive",
      "--database-max-connections", "10", # max number of concurrent database connections
    ]
    ports:
      - 8888:8000